### ISSUE TITLE
 ABM de Cruceros.

### ISSUE THREAD

**Issue by Muabid** [Muabid/ggd-macaco-not-null#4]
- [x] Alta
- [x] Modificación
- [ ] Baja

**Comment by alexisnikc** [comment]
Se agrega Pantalla de Baja con fecha de reinicio de servicio, fecha fuera de servicio y motivo de la baja.

**Comment by carlosnikc** [comment]
Se puede cerrar el Issue?

**Comment by GuilleVerdile** [comment]
Falta hacer la baja del cruceros.

**Comment by mackhood** [comment]
AGREGAR BAJA A CRUCERO ------------ -------- EN LA PANTALLA DE DAR DE BAJA A UN CRUCERO, AGREGAR UN COMBOBOX AL FINAL EN DONDE EL ADMIN TENGA A ELEGIR LO QUE SE DEBE HACER CON LOS PASAJES VENDIDOS DE TODOS LOS VIAJES QUE REALIZABA EL CRUCERO (CANCELAR LOS PASAJES O REEMPLAZAR EL CRUCERO POR OTRO) --- ------- ESTO HACE QUE LUEGO DE ESTE PROCEDURE, SE DEBA EJECUTAR ALGUNO DE LOS 2 DE ABAJO, DEPENDIENDO DE LA OPCION ELEGIDA ------------ CREATE PROCEDURE [MACACO_NOT_NULL].Agregar
02:25Remitente desconocido---- CANCELACION DE PASAJES VENDIDOS --------------------------- ----------- SE EJECUTAR LUEGO DE AGREGAR UNA BAJA A UN CRUCERO (SIEMPRE Y CUANDO LA ACCION POSTERIOR ELEGIDA POR EL ADMIN ERA CANCELAR LOS PASAJES VENDIDOS DEL VIAJE) ------------ -- REALIZA 4 CONSULTAS: -- 1) BORRA LOS MEDIOS DE PAGOS ASOCIADOS AL PAGO DE LOS PASAJES CUYO VIAJE LO REALIZA EL CRUCERO QUE SE ACABA DE DAR DE BAJA -- 2) BORRA EL PAGO ASOCIADO -- 3) SETEA LA FOREIGN KEY DE LOS PASAJES CANCELADOS, RELACIONANDOLOS CON LA

**Comment by GuilleVerdile** [comment]
---------- STATUS BAJA CRUCERO :: ----------
Ya funciona correctamente  la cancelacion de pasajes vendidos y las reservas efectuadas de los viajes del crucero que se da de baja.
Falta probar la logica de los procedures de reemplazar crucero que hizo Ger. Pero ademas, una vez que se reeemplaza el crucero  hay q hacer un if que si NO se encontro un crucero reemplazante se debe ir automaticamente a la pantalla de Alta de un nuevo crucero y se crea un crucero con las mismas características (minimamente) del crucero q se dio de baja. Luego de darlo de alta se le asignan a ese crucero TODOS los viajes que hacia el crucero que se dio de baja.  
TIP:  cuando se llama a la pantalla de alta se le asignan  (en el constructor de  la ventana - abajo del InitialiceComponents() ) al crucero todos los tipos de cabina y las cantidades que tenian el crucero que se dio de baja. Le dejas al usuario si queres que modifique la cantidad de cabinas, pero minimameente tiene que tener las mismas cantidades y tipo que el otro.

**Comment by GuilleVerdile** [comment]
Despues cuando ande todo. 
Sacar el combobox que dice que hacer con los pasajes (cancelar o reemplazar el crucero), y cambiarlo por un parametro mas en el archivo de configuracion. Y que en el if que hizo ger en vez de preguntar por el text del combobox , preguntar por el parametro.
