### ISSUE TITLE
Listado Estadístico

### ISSUE THREAD

**Issue by Muabid** [Muabid/ggd-macaco-not-null#8]
- [ ] Top 5 de los recorridos con más pasajes comprados. 

- [ ] Top 5 de los recorridos con más cabinas libres en cada uno de los viajes
realizados. 

- [ ] Top 5 de los cruceros con mayor cantidad de días fuera de servicio.

**Comment by GuilleVerdile** [comment]
que falta de esto? ya lo habia hecho hace banda, y lo de los botones de ver mas info me dijiste q lo habias agregado ya

**Comment by Muabid** [comment]
> que falta de esto? ya lo habia hecho hace banda, y lo de los botones de ver mas info me dijiste q lo habias agregado ya

@GuilleVerdile  Por ejemplo buscas con el año 1900 y te trae cosas. No debería traer nada  y mostrar un cartel que diga no se encontraron resultados (para mi). Sino pareciera que está funcionando mal. 

![image](https://user-images.githubusercontent.com/29739278/59170381-b42d8680-8b14-11e9-9b73-020676bdf506.png)

**Comment by GuilleVerdile** [comment]
Problema solucionado
